# docker-compose.yml
version: '3.8'
services:
  weather-service:
    build: ./weather-service
    ports:
      - "5001:5001"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    env_file:
      - .env
    networks:
      - smart-wardrobe-network

  outfit-service:
    build: ./outfit-service
    ports:
      - "5002:5002"
    networks:
      - smart-wardrobe-network
  
  wardrobe-service:
  build: ./wardrobe-service
  ports:
    - "5003:5003"
  networks:
      - smart-wardrobe-network

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - WEATHER_SERVICE_URL=http://weather-service:5001
      - OUTFIT_SERVICE_URL=http://outfit-service:5002
      - WARDROBE_SERVICE_URL=http://wardrobe-service:5003
    depends_on:
      - weather-service
      - outfit-service
      - wardrobe-service
    networks:
      - smart-wardrobe-network

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - gateway
    networks:
      - smart-wardrobe-network

networks:
  smart-wardrobe-network:
    driver: bridge